version: '3.4'

# Глобальная настрока логирования.
x-logging:
  &default-logging
  options:
    max-size: '100k'
    max-file: '3'
  driver: json-file

services:
# Кэш сервер для диалогового процессора.
  memcached.local:
    image: memcached
    env_file:
      - .env
    restart: always
    logging: *default-logging
  engine:
    build: .
    env_file:
      - .env
    environment:
      - IFS_CACHE_SERVERS=memcached.local:11211
    ports:
      - 2255:2255
    volumes:
      - ./dldata:/dldata
    depends_on:
      - memcached.local