version: '3'

services:
  memcached.local:
    image: memcached
  engine:
    build: .
    environment:
      - APS_MAX_FILTERS=1
      - APS_START_FILTERS=0
      - APS_MIN_FILTERS=0
      - APS_LOG_LEVEL=4
      - IFS_LOG_LEVEL=DEBUG
      - IFS_LOG_DATA_FLOW=TRUE
      - IFS_CACHE_SERVERS=memcached.local:11211
      - IFS_CACHE_TTL=604800
    ports:
      - 2255:2255
    volumes:
      - ./dldata:/dldata
    depends_on:
      - memcached.local